"""Critic node — evaluates cover letters on 5 dimensions with Best-of-N tracking."""

import logging

from langchain_core.messages import SystemMessage
from langchain_core.runnables import RunnableConfig
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from app.config import get_settings
from app.models.state import AgentState
from app.tools.retry import async_retry
from app.graph.pubsub import log_emitter

logger = logging.getLogger(__name__)


@async_retry(max_retries=2, backoff_base=1.0)
async def _invoke_critic_llm(structured_llm: object, messages: list, run_id: str) -> object:
    """Retry-wrapped critic evaluation call."""
    return await structured_llm.ainvoke(  # type: ignore[union-attr]
        messages,
        config={"metadata": {"node": "critic", "run_id": run_id, "model_tier": "critic"}},
    )


# ---------------------------------------------------------------------------
# Structured output schema
# ---------------------------------------------------------------------------


class CriticEvaluation(BaseModel):
    """5-dimension cover letter evaluation."""

    relevance: int = Field(ge=0, le=100, description="Addresses specific job requirements")
    tone: int = Field(ge=0, le=100, description="Appropriate and consistent tone")
    structure: int = Field(ge=0, le=100, description="Well-organized with clear flow")
    specificity: int = Field(ge=0, le=100, description="Concrete examples and details")
    persuasiveness: int = Field(ge=0, le=100, description="Would motivate a recruiter to call")
    overall: int = Field(ge=0, le=100, description="Weighted overall score")
    feedback: str = Field(description="Specific, actionable improvement suggestions")


SYSTEM_PROMPT = (
    "You are a senior HR director with 20 years of experience reviewing cover letters. "
    "Evaluate the letter critically and honestly against the job requirements. "
    "Weight the overall score: relevance 30%, persuasiveness 25%, specificity 20%, "
    "tone 15%, structure 10%."
)


async def critic_node(state: AgentState, config: RunnableConfig) -> AgentState:
    """Evaluate the cover letter on 5 dimensions using structured output.

    Best-of-N tracking: After scoring, compares with the current best draft
    and updates best_draft/best_score if this revision scores higher.
    This ensures the user always sees the highest-quality draft in HITL-2.
    """
    letter = state.get("draft_letter", "")
    offer = state.get("selected_offer", {})
    structured_offer = offer.get("structured", {})
    revision_count = state.get("revision_count", 0)

    required_skills = structured_offer.get("required_skills") or \
        state.get("gap_report", {}).get("missing_skills", [])

    logger.info(
        "Critic: evaluating letter (revision=%d) for run=%s",
        revision_count,
        state.get("run_id"),
    )
    await log_emitter.emit(state.get("run_id"), {
        "type": "info",
        "message": "Critic: Evaluating draft letter against 5 quality dimensions...",
    })

    settings = get_settings()
    llm = ChatOpenAI(
        model=settings.critic_model,
        api_key=settings.openai_api_key,
        temperature=0,
    )
    structured_llm = llm.with_structured_output(CriticEvaluation)

    # Use offer_summary if available (generated by Matcher), fall back to raw fields
    offer_context = state.get("offer_summary") or (
        f"Title: {offer.get('title', 'Unknown')}\n"
        f"Company: {offer.get('company', 'Unknown')}\n"
        f"Required skills: {', '.join(required_skills) if required_skills else 'not specified'}"
    )

    await log_emitter.emit(state.get("run_id"), {
        "type": "agent_action",
        "message": "Critic analyzing letter relevance, tone, persuasiveness...",
    })

    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        SystemMessage(
            content=f"JOB OFFER:\n{offer_context}\n\nCOVER LETTER:\n{letter}"
        ),
    ]

    try:
        evaluation: CriticEvaluation = await _invoke_critic_llm(  # type: ignore[assignment]
            structured_llm, messages, run_id=state.get("run_id", "")
        )
    except Exception as exc:
        logger.warning(
            "Critic: evaluation failed after retries for run=%s: %s — using fallback score",
            state.get("run_id"), exc,
        )
        evaluation = CriticEvaluation(
            relevance=70, tone=70, structure=70, specificity=70, persuasiveness=70,
            overall=70,
            feedback="Evaluation unavailable. Please review the letter manually.",
        )

    current_score = evaluation.overall
    best_score_so_far = state.get("best_score", 0)

    logger.info(
        "Critic: overall=%d (best_so_far=%d, threshold=%d) for run=%s",
        current_score,
        best_score_so_far,
        settings.critic_threshold,
        state.get("run_id"),
    )
    await log_emitter.emit(state.get("run_id"), {
        "type": "info",
        "message": f"Critic: Score {current_score}/100 (best so far: {max(current_score, best_score_so_far)}/100).",
    })

    # --- Best-of-N tracking ---
    # Record this draft in history
    draft_entry = {
        "draft": letter,
        "score": current_score,
        "revision": revision_count,
        "feedback": evaluation.feedback,
    }

    result: dict = {
        "critic_score": current_score,
        "critic_feedback": evaluation.model_dump(),
        "draft_history": [draft_entry],  # Appends via operator.add reducer
        "status": "critiquing",
    }

    # Update best_draft only if this revision is better (or it's the first one)
    if current_score >= best_score_so_far or best_score_so_far == 0:
        result["best_draft"] = letter
        result["best_score"] = current_score
        result["best_feedback"] = evaluation.model_dump()
        logger.info(
            "Critic: new best draft! score=%d (was %d) for run=%s",
            current_score,
            best_score_so_far,
            state.get("run_id"),
        )
        await log_emitter.emit(state.get("run_id"), {
            "type": "info",
            "message": f"Critic: ⭐ New best draft! Score improved to {current_score}/100.",
        })
    else:
        await log_emitter.emit(state.get("run_id"), {
            "type": "info",
            "message": (
                f"Critic: This revision scored {current_score}/100, "
                f"keeping previous best at {best_score_so_far}/100."
            ),
        })

    return result
